// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
problem[2] = {
  answer:4613732,
  solver:function() {
    let res=0;
    for(let fib of fibonacci()) {
      if (fib>4000000) break;
      if (fib%2===0) res+=fib;
    }
    return res;
  }
};
